---
- name: Cau hinh tren Switch
  hosts: SW1
  gather_facts: no
  tasks:
   - name: tao vlan
  ios_vlan:
  aggregate:
   - { vlan_id : 10 }
   - { vlan_id : 20 }
   - { vlan_id : 30 }
- name: gan cong vao vlan
  ios_l2_interface:
   name: "{{ item.int }}"
   mode: access
   access_vlan: "{{ item.vlan }}"
  with_items: # thay the cac cong
   - { vlan: "10", int: "fastEthernet3/0/2"}
   - { vlan: "20", int: "fastEthernet3/0/3"}
   - { vlan: "30", int: "fastEthernet3/0/4"}
